/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/button/BaseButton.vue')['default']
    BaseIcon: typeof import('./src/components/base/icon/BaseIcon.vue')['default']
    BasePopover: typeof import('./src/components/base/popover/BasePopover.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    IAntDesignAlipayCircleFilled: typeof import('~icons/ant-design/alipay-circle-filled')['default']
    IBxBxsConversation: typeof import('~icons/bx/bxs-conversation')['default']
    IBxBxsMessage: typeof import('~icons/bx/bxs-message')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpChatDotSquare: typeof import('~icons/ep/chat-dot-square')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    LayoutLoading: typeof import('./src/components/base/loading/LayoutLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheLayout: typeof import('./src/components/layout/TheLayout.vue')['default']
    TheSidebar: typeof import('./src/components/layout/TheSidebar.vue')['default']
  }
}
