/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/button/BaseButton.vue')['default']
    BaseIcon: typeof import('./src/components/base/icon/BaseIcon.vue')['default']
    BasePopover: typeof import('./src/components/base/popover/BasePopover.vue')['default']
    BasePopup: typeof import('./src/components/base/popup/BasePopup.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    IAntDesignUserAddOutlined: typeof import('~icons/ant-design/user-add-outlined')['default']
    IAntDesignUsergroupAddOutlined: typeof import('~icons/ant-design/usergroup-add-outlined')['default']
    IBxBxsContact: typeof import('~icons/bx/bxs-contact')['default']
    IBxBxsMessage: typeof import('~icons/bx/bxs-message')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    LayoutLoading: typeof import('./src/components/base/loading/LayoutLoading.vue')['default']
    PopupDetailUser: typeof import('./src/components/popup/PopupDetailUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheLayout: typeof import('./src/components/layout/TheLayout.vue')['default']
    TheNav: typeof import('./src/components/layout/TheNav.vue')['default']
    TheSidebar: typeof import('./src/components/layout/TheSidebar.vue')['default']
    ThumbConversation: typeof import('./src/components/base/thumb/ThumbConversation.vue')['default']
  }
}
